# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parsecdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainform(object):
    def setupUi(self, Mainform):
        Mainform.setObjectName("Mainform")
        Mainform.setEnabled(True)
        Mainform.resize(910, 579)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Mainform.sizePolicy().hasHeightForWidth())
        Mainform.setSizePolicy(sizePolicy)
        Mainform.setMinimumSize(QtCore.QSize(1, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/picture/k5.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mainform.setWindowIcon(icon)
        Mainform.setAutoFillBackground(True)
        Mainform.setStyleSheet("")
        self.Title = QtWidgets.QLabel(Mainform)
        self.Title.setGeometry(QtCore.QRect(310, 30, 301, 30))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title.setObjectName("Title")
        self.doors_text = QtWidgets.QTextEdit(Mainform)
        self.doors_text.setGeometry(QtCore.QRect(20, 230, 861, 291))
        self.doors_text.setToolTip("")
        self.doors_text.setObjectName("doors_text")
        self.start = QtWidgets.QPushButton(Mainform)
        self.start.setGeometry(QtCore.QRect(20, 170, 861, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/picture/k3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon1)
        self.start.setObjectName("start")
        self.bottom = QtWidgets.QLabel(Mainform)
        self.bottom.setGeometry(QtCore.QRect(310, 530, 301, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bottom.setFont(font)
        self.bottom.setObjectName("bottom")
        self.filepath = QtWidgets.QLineEdit(Mainform)
        self.filepath.setGeometry(QtCore.QRect(20, 103, 701, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filepath.sizePolicy().hasHeightForWidth())
        self.filepath.setSizePolicy(sizePolicy)
        self.filepath.setMinimumSize(QtCore.QSize(660, 46))
        self.filepath.setMaximumSize(QtCore.QSize(16777215, 20))
        self.filepath.setMouseTracking(True)
        self.filepath.setObjectName("filepath")
        self.openfile = QtWidgets.QPushButton(Mainform)
        self.openfile.setEnabled(True)
        self.openfile.setGeometry(QtCore.QRect(738, 100, 141, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openfile.sizePolicy().hasHeightForWidth())
        self.openfile.setSizePolicy(sizePolicy)
        self.openfile.setMinimumSize(QtCore.QSize(93, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openfile.setFont(font)
        self.openfile.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/picture/k2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openfile.setIcon(icon2)
        self.openfile.setAutoRepeatInterval(99)
        self.openfile.setObjectName("openfile")

        self.retranslateUi(Mainform)
        QtCore.QMetaObject.connectSlotsByName(Mainform)

    def retranslateUi(self, Mainform):
        _translate = QtCore.QCoreApplication.translate
        Mainform.setWindowTitle(_translate("Mainform", "Dialog"))
        self.Title.setText(_translate("Mainform",
                                      "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                      "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                      "p, li { white-space: pre-wrap; }\n"
                                      "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                      "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#000000;\">Parse CDD File Tool</span></p></body></html>"))
        self.start.setText(_translate("Mainform", "Start"))
        self.bottom.setText(_translate("Mainform", "©CSDN 蚂蚁小兵"))
        self.openfile.setToolTip(_translate("Mainform", "<html><head/><body><p>Chose your DBC file</p></body></html>"))
        self.openfile.setText(_translate("Mainform", "OpenFile"))

import photo
